### ISSUE TITLE
Criar site do GrupyDF

### ISSUE THREAD

**Issue by magnunleno** [grupydf/grupy-df.gerenciamento#6]
Criar um site para divulgação do GrupyDF, com uma página inicial de "boas vindas", páginas sobre a comunidade e uma seção de notícias (posts) para publicarmos eventos, fotos e etc.

**Comment by gilsondev** [comment]
Depois coloca um print do protótipo que fez. Ficou muito bom.

**Comment by humrochagf** [comment]
Pode dar close nesse aqui né?

**Comment by magnunleno** [comment]
Ainda não está 100% pronto, mas vou fechar essa issue....

**Comment by humrochagf** [comment]
Só deixar como referência aqui os issues do site vão estar em https://github.com/grupydf/grupydf.github.io/issues pra quem quiser colaborar, vou mover o que estiver faltando deste issue pra lá
